In [25]:
import pandas as pd
import numpy as np

ag = pd.read_csv("nass-plum-apricot-stats-cleaned.csv")

In [17]:
ag.head()

,Program,Year,Period,Geo Level,State,State ANSI,Ag District,Ag District Code,County,County ANSI,Commodity,Data Item,Domain,Domain Category,Value,CV (%)
0,CENSUS,2022,YEAR,COUNTY,ALABAMA,1.0,UPPER PLAINS & PIEDMONT,30.0,PICKENS,107.0,PLUM-APRICOT HYBRIDS,"PLUM-APRICOT HYBRIDS, INCL PLUMCOTS & PLUOTS -...",TOTAL,NOT SPECIFIED,(D),(D)
1,CENSUS,2022,YEAR,COUNTY,ALABAMA,1.0,UPPER PLAINS & PIEDMONT,30.0,PICKENS,107.0,PLUM-APRICOT HYBRIDS,"PLUM-APRICOT HYBRIDS, INCL PLUMCOTS & PLUOTS -...",TOTAL,NOT SPECIFIED,(D),(D)
2,CENSUS,2022,YEAR,COUNTY,ALABAMA,1.0,UPPER PLAINS & PIEDMONT,30.0,PICKENS,107.0,PLUM-APRICOT HYBRIDS,"PLUM-APRICOT HYBRIDS, INCL PLUMCOTS & PLUOTS -...",TOTAL,NOT SPECIFIED,1,42.1
3,CENSUS,2022,YEAR,COUNTY,ALABAMA,1.0,UPPER PLAINS & PIEDMONT,30.0,PICKENS,107.0,PLUM-APRICOT HYBRIDS,"PLUM-APRICOT HYBRIDS, INCL PLUMCOTS & PLUOTS -...",TOTAL,NOT SPECIFIED,1,42.4
4,CENSUS,2022,YEAR,COUNTY,ALABAMA,1.0,WIREGRASS,60.0,GENEVA,61.0,PLUM-APRICOT HYBRIDS,"PLUM-APRICOT HYBRIDS, INCL PLUMCOTS & PLUOTS -...",TOTAL,NOT SPECIFIED,(D),(D)

In [18]:
ag.shape

(2403, 16)

In [19]:
ag.dtypes

Program              object
Year                  int64
Period               object
Geo Level            object
State                object
State ANSI          float64
Ag District          object
Ag District Code    float64
County               object
County ANSI         float64
Commodity            object
Data Item            object
Domain               object
Domain Category      object
Value                object
CV (%)               object
dtype: object

In [37]:
ag_cleaned = ag.drop(columns=['Program', 'Period', 'State ANSI', 'Ag District Code', 'County ANSI', 'Commodity', 'CV (%)'])
ag_cleaned.head()

,Year,Geo Level,State,Ag District,County,Data Item,Domain,Domain Category,Value
0,2022,COUNTY,ALABAMA,UPPER PLAINS & PIEDMONT,PICKENS,"PLUM-APRICOT HYBRIDS, INCL PLUMCOTS & PLUOTS -...",TOTAL,NOT SPECIFIED,(D)
1,2022,COUNTY,ALABAMA,UPPER PLAINS & PIEDMONT,PICKENS,"PLUM-APRICOT HYBRIDS, INCL PLUMCOTS & PLUOTS -...",TOTAL,NOT SPECIFIED,(D)
2,2022,COUNTY,ALABAMA,UPPER PLAINS & PIEDMONT,PICKENS,"PLUM-APRICOT HYBRIDS, INCL PLUMCOTS & PLUOTS -...",TOTAL,NOT SPECIFIED,1
3,2022,COUNTY,ALABAMA,UPPER PLAINS & PIEDMONT,PICKENS,"PLUM-APRICOT HYBRIDS, INCL PLUMCOTS & PLUOTS -...",TOTAL,NOT SPECIFIED,1
4,2022,COUNTY,ALABAMA,WIREGRASS,GENEVA,"PLUM-APRICOT HYBRIDS, INCL PLUMCOTS & PLUOTS -...",TOTAL,NOT SPECIFIED,(D)

In [38]:
ag_cleaned['Data Item'] = ag_cleaned['Data Item'].str.replace('PLUM-APRICOT HYBRIDS, INCL PLUMCOTS & PLUOTS - ', '')

In [52]:
ag_us_total = ag_cleaned.query('`Geo Level` == "NATIONAL" and Domain == "TOTAL"')
ag_us_total.head(30)

,Year,Geo Level,State,Ag District,County,Data Item,Domain,Domain Category,Value
942,2022,NATIONAL,US TOTAL,NaN,NaN,ACRES BEARING,TOTAL,NOT SPECIFIED,"3,291"
950,2022,NATIONAL,US TOTAL,NaN,NaN,ACRES BEARING & NON-BEARING,TOTAL,NOT SPECIFIED,"3,554"
957,2022,NATIONAL,US TOTAL,NaN,NaN,ACRES NON-BEARING,TOTAL,NOT SPECIFIED,262
965,2022,NATIONAL,US TOTAL,NaN,NaN,OPERATIONS WITH AREA BEARING,TOTAL,NOT SPECIFIED,484
973,2022,NATIONAL,US TOTAL,NaN,NaN,OPERATIONS WITH AREA BEARING & NON-BEARING,TOTAL,NOT SPECIFIED,729
980,2022,NATIONAL,US TOTAL,NaN,NaN,OPERATIONS WITH AREA NON-BEARING,TOTAL,NOT SPECIFIED,350
1662,2017,NATIONAL,US TOTAL,NaN,NaN,ACRES BEARING,TOTAL,NOT SPECIFIED,"4,266"
1670,2017,NATIONAL,US TOTAL,NaN,NaN,ACRES BEARING & NON-BEARING,TOTAL,NOT SPECIFIED,"4,767"
1678,2017,NATIONAL,US TOTAL,NaN,NaN,ACRES NON-BEARING,TOTAL,NOT SPECIFIED,501
1686,2017,NATIONAL,US TOTAL,NaN,NaN,OPERATIONS WITH AREA BEARING,TOTAL,NOT SPECIFIED,350
1694,2017,NATIONAL,US TOTAL,NaN,NaN,OPERATIONS WITH AREA BEARING & NON-BEARING,TOTAL,NOT SPECIFIED,506
1702,2017,NATIONAL,US TOTAL,NaN,NaN,OPERATIONS WITH AREA NON-BEARING,TOTAL,NOT SPECIFIED,200
2083,2012,NATIONAL,US TOTAL,NaN,NaN,ACRES BEARING,TOTAL,NOT SPECIFIED,"3,002"
2084,2012,NATIONAL,US TOTAL,NaN,NaN,ACRES BEARING & NON-BEARING,TOTAL,NOT SPECIFIED,"3,317"
2085,2012,NATIONAL,US TOTAL,NaN,NaN,ACRES NON-BEARING,TOTAL,NOT SPECIFIED,315
2086,2012,NATIONAL,US TOTAL,NaN,NaN,OPERATIONS WITH AREA BEARING,TOTAL,NOT SPECIFIED,184
2087,2012,NATIONAL,US TOTAL,NaN,NaN,OPERATIONS WITH AREA BEARING & NON-BEARING,TOTAL,NOT SPECIFIED,223
2088,2012,NATIONAL,US TOTAL,NaN,NaN,OPERATIONS WITH AREA NON-BEARING,TOTAL,NOT SPECIFIED,72
2373,2007,NATIONAL,US TOTAL,NaN,NaN,ACRES BEARING,TOTAL,NOT SPECIFIED,"3,843"
2374,2007,NATIONAL,US TOTAL,NaN,NaN,ACRES BEARING & NON-BEARING,TOTAL,NOT SPECIFIED,"4,332"
2375,2007,NATIONAL,US TOTAL,NaN,NaN,ACRES NON-BEARING,TOTAL,NOT SPECIFIED,489
2376,2007,NATIONAL,US TOTAL,NaN,NaN,OPERATIONS WITH AREA BEARING,TOTAL,NOT SPECIFIED,258
2377,2007,NATIONAL,US TOTAL,NaN,NaN,OPERATIONS WITH AREA BEARING & NON-BEARING,TOTAL,NOT SPECIFIED,308
2378,2007,NATIONAL,US TOTAL,NaN,NaN,OPERATIONS WITH AREA NON-BEARING,TOTAL,NOT SPECIFIED,97

In [59]:
ag_us_total['Value'] = ag_us_total['Value'].str.replace(',', '')

/var/folders/bq/_d8c7p312s33ztrq6l6cf91c0000gn/T/ipykernel_44557/2183874918.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ag_us_total['Value'] = ag_us_total['Value'].str.replace(',', '')

In [60]:
ag_us_total['Value'] = ag_us_total['Value'].astype('Int64')

/var/folders/bq/_d8c7p312s33ztrq6l6cf91c0000gn/T/ipykernel_44557/3289002223.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ag_us_total['Value'] = ag_us_total['Value'].astype('Int64')

In [61]:
ag_us_total_all = ag_us_total['Data Item'].isin(['ACRES BEARING & NON-BEARING', 'OPERATIONS WITH AREA BEARING & NON-BEARING'])

In [62]:
ag_us_total_all['Value'].plot(kind='bar')

KeyError: 'Value'